title: 2025-1학기 사회글 008
description: 2025-1학기 사회과학글쓰기 008 제출과제
theme: just-the-docs

url: https://DeepWrite.github.io/2025-1-008

aux_links:
  강의자료 홈페이지로 돌아가기: https://deepwrite.github.io/2025SPRING/

just_the_docs:
  search:
    tokenizer_separator: /[\s\-_ㄱ-ㅎ가-힣]+/
    preview_length: 200